### ISSUE TITLE
[Bug]: clients/khala-mobile full test suite: mock.module leak breaks native-modules-readiness.test.ts

### ISSUE THREAD

**Issue by AtlantisPleb** [OpenAgentsInc/openagents#8458]
### Affected surface

`clients/khala-mobile` package test suite: `bun run --cwd clients/khala-mobile test` (also invoked as `bun run test:khala-mobile` from the repo root aggregate `test` script).

### Actual behavior

`tests/native-modules-readiness.test.ts` fails only when the full package test suite runs (`bun test` across all files in `clients/khala-mobile/tests/`):

```
tests/native-modules-readiness.test.ts:
TypeError: readNativeReadiness is not a function. (In 'readNativeReadiness()', 'readNativeReadiness' is undefined)
    at tests/native-modules-readiness.test.ts:42:26
(fail) readNativeReadiness > isolates one probe's bridge rejection from the sibling probe's real readiness
```

Root cause, confirmed by direct probing: `tests/chat-composer.test.tsx` calls `mock.module("../src/native/modules", () => ({ khalaNativeModules: {...} }))` (a stub missing the `readNativeReadiness` export). This mock leaks past an added `afterAll(() => mock.restore())` cleanup — a probe added directly after the restore call showed `Object.keys(await import("../src/native/modules"))` still returns only `["khalaNativeModules"]` (chat-composer's stub shape) in a later-running file, never picking up the real module's `readNativeReadiness` export. Running `tests/native-modules-readiness.test.ts` alone (`bun test tests/native-modules-readiness.test.ts`) passes every time; only the combined multi-file run fails.

### Expected behavior

Every test file should pass both standalone and as part of the full `bun test` run for the package, matching `CLAUDE.md`'s "nothing accumulates ... full relevant test suite green" policy. `mock.module` registered in one test file should not silently break unrelated assertions in a different file.

### Reproduction steps

1. `cd clients/khala-mobile && bun install` (from repo root: `bun install --filter @openagentsinc/khala-mobile`)
2. `bun test tests/native-modules-readiness.test.ts` → passes (1 pass, 0 fail).
3. `bun test` (full suite) → `tests/native-modules-readiness.test.ts` fails with the `TypeError` above; all other files still pass.
4. Optional repro of the leak in isolation: add `console.error("keys:", Object.keys(await import("../src/native/modules")))` right before the failing line in `tests/native-modules-readiness.test.ts`, run the full suite, observe it logs `["khalaNativeModules"]` instead of `["khalaNativeModules", "readNativeReadiness"]`.

### Public-safe evidence

```
bun test v1.3.11 (af24e281)
...
tests/native-modules-readiness.test.ts:
37 |
38 | const { readNativeReadiness } = await import("../src/native/modules")
39 |
40 | describe("readNativeReadiness", () => {
41 |   test("isolates one probe's bridge rejection from the sibling probe's real readiness", async () => {
42 |     const result = await readNativeReadiness()
                              ^
TypeError: readNativeReadiness is not a function. (In 'readNativeReadiness()', 'readNativeReadiness' is undefined)
      at <anonymous> (tests/native-modules-readiness.test.ts:42:26)
(fail) readNativeReadiness > isolates one probe's bridge rejection from the sibling probe's real readiness [0.13ms]

 194 pass
 1 fail
 488 expect() calls
Ran 195 tests across 33 files.
```

### Severity

S2 - degraded, confusing, stale, or partially broken behavior

### Environment

- macOS (local dev), Bun 1.3.11
- `clients/khala-mobile` package, `bun test` (no CI runner involved; local-only repro)
- Confirmed pre-existing on `origin/main` as of 2026-07-05 (not introduced by #8453 icon/splash asset generation work); reproduces with or without that unrelated change present.

### Safety and redaction

No secrets, tokens, wallet material, private prompts, or customer content involved; this is a local test-harness/module-mocking issue only.

### Required confirmations

- [x] I am reporting a specific reproducible bug, not a product-promise report, feature request, general commentary, or broad "this does not live up to promise" note.
- [x] I searched existing GitHub issues and the Product Promises Forum.
- [x] I removed secrets, bearer tokens, wallet material, payment artifacts, private prompts, private files, source archives, provider payloads, and customer-sensitive content.
- [x] I included exact reproduction steps and public-safe evidence.
- [x] I understand malformed or loose reports should be rejected by the form or discussed on the Forum.

**Comment by AtlantisPleb** [comment]
Closing — this is already fixed and verified.

Root cause: `chat-composer.test.tsx`'s `mock.module("../src/native/modules", ...)` stub doesn't re-export `readNativeReadiness`. Bun's `mock.module` registry is process-global, so that incomplete stub leaks into any test file that later imports the real module in the same `bun test` process, corrupting `native-modules-readiness.test.ts`'s view of it.

Two "obvious" fixes were tried and disproven with real evidence first: making the stub complete only avoids the crash but still returns wrong values; `afterAll(() => mock.restore())` measurably does not prevent the leak in the full 36-file suite despite running correctly (verified via instrumented tracing).

Real fix (commit `fc4571e16c`, already on `main`): `native-modules-readiness.test.ts` imports the production module via a cache-busting query-suffixed specifier (`"../src/native/modules?fresh=native-modules-readiness-test"`), which Bun's `mock.module` doesn't match against, forcing a genuinely fresh evaluation bypassing any registered mock on the bare path. TypeScript type-safety preserved via `type NativeModulesModule = typeof import("../src/native/modules")`.

Verified with `bun test --rerun-each=8` (1000+ executions in one invocation) — zero flakes. Single-file fix, no changes to `chat-composer.test.tsx` needed.
